jobs:
- job: windows_x86_64
  displayName: 'Windows (x86_64)'
  pool:
    vmImage: windows-latest
  steps:
  - template: "azure-pipelines-win-steps.yml"
    parameters:
      bits: "64"
- job: windows_x86
  displayName: 'Windows (x86)'
  pool:
    vmImage: windows-latest
  steps:
  - template: "azure-pipelines-win-steps.yml"
    parameters:
      bits: "32"
